// <auto-generated />
namespace OneBox_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class email_to_container_table_delete_containername_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(email_to_container_table_delete_containername_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201604282159284_email_to_container_table_delete_containername_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
