// <auto-generated />
namespace OneBox_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class resetEmailtable_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetEmailtable_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201605151125406_resetEmailtable_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
