// <auto-generated />
namespace OneBox_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_virtualblob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_virtualblob));
        
        string IMigrationMetadata.Id
        {
            get { return "201605082312572_added_virtualblob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
